/**
 * OEML - REST API
 * This section will provide necessary information about the `CoinAPI OEML REST API` protocol. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class ExecutionReportAllOf (
  /* Hash client id */
  clientOrderIdFormatExchange: Option[String] = None,
  /* Exchange order id */
  exchangeOrderId: Option[String] = None,
  /* Amount open */
  amountOpen: Option[Double] = None,
  /* Amount filled */
  amountFilled: Option[Double] = None,
  status: Option[OrdStatus] = None,
  /* History of order status changes */
  timeOrder: Option[Seq[Seq[String]]] = None,
  /* Error message */
  errorMessage: Option[String] = None
) extends ApiModel


