/**
 * OEML - REST API
 * This section will provide necessary information about the `CoinAPI OEML REST API` protocol. 
 *
 * The version of the OpenAPI document: v1
 * Contact: support@coinapi.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class BalanceData {
    /**
    * Exchange currency code.
    */
    'symbolExchange'?: string;
    /**
    * CoinAPI currency code.
    */
    'symbolCoinapi'?: string;
    /**
    * Value of the current total currency balance on the exchange.
    */
    'balance'?: number;
    /**
    * Value of the current available currency balance on the exchange that can be used as collateral.
    */
    'available'?: number;
    /**
    * Value of the current locked currency balance by the exchange.
    */
    'locked'?: number;
    /**
    * Source of the last modification. 
    */
    'updateOrigin'?: BalanceData.UpdateOriginEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "symbolExchange",
            "baseName": "symbol_exchange",
            "type": "string"
        },
        {
            "name": "symbolCoinapi",
            "baseName": "symbol_coinapi",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "available",
            "baseName": "available",
            "type": "number"
        },
        {
            "name": "locked",
            "baseName": "locked",
            "type": "number"
        },
        {
            "name": "updateOrigin",
            "baseName": "update_origin",
            "type": "BalanceData.UpdateOriginEnum"
        }    ];

    static getAttributeTypeMap() {
        return BalanceData.attributeTypeMap;
    }
}

export namespace BalanceData {
    export enum UpdateOriginEnum {
        INITIALIZATION = <any> 'INITIALIZATION',
        BALANCEMANAGER = <any> 'BALANCE_MANAGER',
        EXCHANGE = <any> 'EXCHANGE'
    }
}
