{-
   OEML - REST API
   This section will provide necessary information about the `CoinAPI OEML REST API` protocol. 

   The version of the OpenAPI document: v1

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.CreateOrderValidationError exposing (CreateOrderValidationError, decoder, encode, encodeWithTag, toString)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias CreateOrderValidationError =
    { type_ : Maybe (String)
    , title : Maybe (String)
    , status : Maybe (Float)
    , traceId : Maybe (String)
    , errors : Maybe (String)
    }


decoder : Decoder CreateOrderValidationError
decoder =
    Decode.succeed CreateOrderValidationError
        |> optional "type" (Decode.nullable Decode.string) Nothing
        |> optional "title" (Decode.nullable Decode.string) Nothing
        |> optional "status" (Decode.nullable Decode.float) Nothing
        |> optional "traceId" (Decode.nullable Decode.string) Nothing
        |> optional "errors" (Decode.nullable Decode.string) Nothing



encode : CreateOrderValidationError -> Encode.Value
encode =
    Encode.object << encodePairs


encodeWithTag : ( String, String ) -> CreateOrderValidationError -> Encode.Value
encodeWithTag (tagField, tag) model =
    Encode.object <| encodePairs model ++ [ ( tagField, Encode.string tag ) ]


encodePairs : CreateOrderValidationError -> List (String, Encode.Value)
encodePairs model =
    [ ( "type", Maybe.withDefault Encode.null (Maybe.map Encode.string model.type_) )
    , ( "title", Maybe.withDefault Encode.null (Maybe.map Encode.string model.title) )
    , ( "status", Maybe.withDefault Encode.null (Maybe.map Encode.float model.status) )
    , ( "traceId", Maybe.withDefault Encode.null (Maybe.map Encode.string model.traceId) )
    , ( "errors", Maybe.withDefault Encode.null (Maybe.map Encode.string model.errors) )
    ]



toString : CreateOrderValidationError -> String
toString =
    Encode.encode 0 << encode




