# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExecutionReportAllOf")

model.instance <- ExecutionReportAllOf$new()

test_that("client_order_id_format_exchange", {
  # tests for the property `client_order_id_format_exchange` (character)
  # Hash client id

  # uncomment below to test the property 
  #expect_equal(model.instance$`client_order_id_format_exchange`, "EXPECTED_RESULT")
})

test_that("exchange_order_id", {
  # tests for the property `exchange_order_id` (character)
  # Exchange order id

  # uncomment below to test the property 
  #expect_equal(model.instance$`exchange_order_id`, "EXPECTED_RESULT")
})

test_that("amount_open", {
  # tests for the property `amount_open` (numeric)
  # Amount open

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount_open`, "EXPECTED_RESULT")
})

test_that("amount_filled", {
  # tests for the property `amount_filled` (numeric)
  # Amount filled

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount_filled`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (OrdStatus)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("time_order", {
  # tests for the property `time_order` (array[array[character]])
  # History of order status changes

  # uncomment below to test the property 
  #expect_equal(model.instance$`time_order`, "EXPECTED_RESULT")
})

test_that("error_message", {
  # tests for the property `error_message` (character)
  # Error message

  # uncomment below to test the property 
  #expect_equal(model.instance$`error_message`, "EXPECTED_RESULT")
})

