/*
 * OEML - REST API
 *
 * This section will provide necessary information about the `CoinAPI OEML REST API` protocol. 
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Balance struct for Balance
type Balance struct {
	// Result type.
	Type string `json:"type,omitempty"`
	// Exchange name.
	ExchangeName string `json:"exchange_name,omitempty"`
	Data []BalanceData `json:"data,omitempty"`
}
