# OEML - REST API
#
# This section will provide necessary information about the `CoinAPI OEML REST API` protocol. 
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CancelOrderAllRequest
#' @description CancelOrderAllRequest Class
#' @format An \code{R6Class} generator object
#' @field exchange_id  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CancelOrderAllRequest <- R6::R6Class(
  'CancelOrderAllRequest',
  public = list(
    `exchange_id` = NULL,
    initialize = function(`exchange_id`, ...){
      local.optional.var <- list(...)
      if (!missing(`exchange_id`)) {
        stopifnot(is.character(`exchange_id`), length(`exchange_id`) == 1)
        self$`exchange_id` <- `exchange_id`
      }
    },
    toJSON = function() {
      CancelOrderAllRequestObject <- list()
      if (!is.null(self$`exchange_id`)) {
        CancelOrderAllRequestObject[['exchange_id']] <-
          self$`exchange_id`
      }

      CancelOrderAllRequestObject
    },
    fromJSON = function(CancelOrderAllRequestJson) {
      CancelOrderAllRequestObject <- jsonlite::fromJSON(CancelOrderAllRequestJson)
      if (!is.null(CancelOrderAllRequestObject$`exchange_id`)) {
        self$`exchange_id` <- CancelOrderAllRequestObject$`exchange_id`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`exchange_id`)) {
        sprintf(
        '"exchange_id":
          "%s"
                ',
        self$`exchange_id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CancelOrderAllRequestJson) {
      CancelOrderAllRequestObject <- jsonlite::fromJSON(CancelOrderAllRequestJson)
      self$`exchange_id` <- CancelOrderAllRequestObject$`exchange_id`
      self
    }
  )
)
