# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OEML-RESTAPI.Model.Balance do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"exchange_name",
    :"data"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t | nil,
    :"exchange_name" => String.t | nil,
    :"data" => [BalanceData] | nil
  }
end

defimpl Poison.Decoder, for: OEML-RESTAPI.Model.Balance do
  import OEML-RESTAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :list, OEML-RESTAPI.Model.BalanceData, options)
  end
end

